package e

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	ERROR_AUTH_CHECK_TOKEN_TIMEOUT   = 1001
	ERROR_AUTH_CHECK_TOKEN_FAIL      = 1002
	ERROR_AUTH_PERMISSION_DENIED     = 1003
	ERROR_AUTH_LOGIN_WRONG_UNAME_PWD = 1004
	ERROR_AUTH_LOGIN_INVALID_SEU_ID  = 1005
	ERROR_AUTH_LOGIN_INVALID_QQ_ID   = 1006

	ERROR_OPERATION_GENERATION = 2001
)
